In [16]:
import mysql.connector
import time
import sys

class Beer:
    pass

##Connecting to the Database
connection = mysql.connector.connect(host='localhost', # Setting up the database connection
                                     database = 'beeronomics',
                                     user='root',
                                     password='Cheers!!')

##Creates Cursors that connect to the database
cursor1 = connection.cursor(buffered = True)
cursor2 = connection.cursor(buffered = True)
cursor3 = connection.cursor(buffered = True)
cursor4 = connection.cursor(buffered = True)
cursor5 = connection.cursor(buffered = True)
cursor6 = connection.cursor(buffered = True)
cursor7 = connection.cursor(buffered = True)
    
##mySQL Query Variables
mySql_Select_Beer_Ids = """SELECT beer_id FROM beer_types"""
mySql_Select_Beer_Names = """SELECT beer_name FROM beer_types"""
mySql_Select_Beer_Prices_Min = """SELECT beer_price_min FROM beer_types"""
mySql_Select_Beer_Prices_Max = """SELECT beer_price_max FROM beer_types"""
mySql_Select_Beer_Prices_Act = """SELECT beer_price_active FROM beer_types"""
mySql_Select_Purchase_Counts = """SELECT purchase_count FROM beer_types"""
mySql_Select_Start_Prices = """SELECT beer_price_start FROM beer_types"""
    
##Executing the Queries and Fetching the Data for Python
records1 = cursor1.execute(mySql_Select_Beer_Ids)
results1 = cursor1.fetchall()
records2 = cursor2.execute(mySql_Select_Beer_Names)
results2 = cursor2.fetchall()
records3 = cursor3.execute(mySql_Select_Beer_Prices_Min)
results3 = cursor3.fetchall()
records4 = cursor4.execute(mySql_Select_Beer_Prices_Max)
results4 = cursor4.fetchall()
records5 = cursor5.execute(mySql_Select_Beer_Prices_Act)
results5 = cursor5.fetchall()
records6 = cursor6.execute(mySql_Select_Purchase_Counts)
results6 = cursor6.fetchall()
records7 = cursor7.execute(mySql_Select_Start_Prices)
results7 = cursor7.fetchall()

rows = cursor1.rowcount

##Creating Empty Lists
beer_ids = []
beer_names = []
beer_prices_min = []
beer_prices_max = []
beer_prices_act = []
purchase_counts = []
beer_prices_start = []
    
##Converting Tuples From mySQL to Lists
for t in results1: 
    for x in t:
        beer_ids.append(x)
#print(beer_ids)
    
for t in results2: 
    for x in t:
        beer_names.append(x)
#print(beer_names)
    
for t in results3: 
    for x in t:
        beer_prices_min.append(x)
#print(beer_prices_min)

for t in results4: 
    for x in t:
        beer_prices_max.append(x)
#print(beer_prices_act)
    
for t in results5: 
    for x in t:
        beer_prices_act.append(x)
#print(beer_prices_start)

for t in results6: 
    for x in t:
        purchase_counts.append(x)
#print(beer_prices_act)

for t in results7: 
    for x in t:
        beer_prices_start.append(x)
#print(beer_prices_act)

#Create Instances of a Class
for i in range(0,rows):
    beer_ids[i] = Beer()
    beer_ids[i].name = beer_names[i]
    beer_ids[i].minprice = beer_prices_min[i]
    beer_ids[i].maxprice = beer_prices_max[i]
    beer_ids[i].actprice = beer_prices_act[i]
    beer_ids[i].purcount = purchase_counts[i]
    beer_ids[i].startprice = beer_prices_start[i]
    print(beer_ids[i].startprice)

5.0
5.0
5.0
5.0
5.0
5.0